---
apiVersion: v1
kind: Service
metadata:
  name: django-dev
spec:
  selector:
    name: django-dev
  ports:
  - port: 10000
    targetPort: 8000
    nodePort: 30000
    protocol: TCP
    name: django-server
  - port: 10001
    targetPort: 8888
    nodePort: 30001
    protocol: TCP
    name: jupyter
  externalIPs:
  - 192.168.0.21
  - 192.168.0.22
  type: NodePort
