apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: pshost01:5000/study/mydjango
    workspace: .
    docker:
      dockerfilePath: ./kubernetes/docker_dev/Dockerfile
  local:
    skipPush: true
deploy:
  helm:
    releases:
    - name: helm-dev
      chartPath: kubernetes/helm
      namespace: myblog-prod
profiles:
  - name: release
    build:
      artifacts:
      - imageName: pshost01:5000/study/mydjango
        workspace: .
        docker:
          dockerfilePath: ./kubernetes/docker_dev/Dockerfile
      local:
        skipPush: false
      tagPolicy:
        gitCommit: {}
    deploy:
      helm:
        releases:
        - name: helm-release
          chartPath: kubernetes/helm
          namespace: myblog-prod
          skipBuildDependencies: true
