apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: pshost01:5000/study/mydjango
    workspace: .
    docker:
      dockerfilePath: ./kubernetes/docker_dev/Dockerfile
  local:
    skipPush: true
deploy:
  helm:
    releases:
    - name: helm-dev
      chartPath: kubernetes/helm
      namespace: myblog-prod
      valuesFiles: kubernetes/dev/values.yaml
      setValues:
        replicaCount: 1
        ingress.enabled: false
        http.port: 8080
        http.nodePort: 30080
        debug.enabled: true
        debug.port: 8081
        debug.nodePort: 30081
profiles:
  - name: release
    build:
      artifacts:
      - imageName: pshost01:5000/study/mydjango
        workspace: .
        docker:
          dockerfilePath: ./kubernetes/docker_dev/Dockerfile
      local:
        skipPush: false
      tagPolicy:
        gitCommit: {}
    deploy:
      kubectl:
        manifests:
        - kubernetes/helm/templates/*.yaml
