# Generated by Django 2.1.2 on 2019-08-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogManager', '0002_auto_20190816_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediatr',
            name='topic',
        ),
    ]
